### ISSUE TITLE
Replace scrapping code

### ISSUE THREAD

**Issue by Foxboron** [briancaffey/AUR-data#1]
Helluw.

Loved the blog post and the generated data. However, there is no need to actually scrape aur after all the packages. A list is generated daily and can be used to pull packages. This decreases the load of an already stressed aurweb application.

https://aur.archlinux.org/packages.gz

**Comment by briancaffey** [comment]
Thanks @Foxboron You are correct, I shouldn't have scrapped the AUR packages since the list is available on the link you mentioned. After I collected the data I also noticed that the path I scrapped is restricted by `robots.txt` on `https://www.archlinux.org/robots.txt`:

```
User-agent: *
Disallow: /packages/search/
Disallow: /packages/?
Disallow: /packages/?*
Sitemap: https://www.archlinux.org/sitemap.xml
Crawl-delay: 2
```

I did make a note of the `packages.gz`  file in the script and I am removing the code for scrapping the lists of AUR packages from `/packages?*`.
